### ISSUE TITLE
Feedback after first testing with real data

### ISSUE THREAD

**Issue by Weiles** [ESA-VirES/Aeolus-Client#37] opened 2018-09-11 06:37 UTC
**Auxiliary files:** 

- The auxiliary files MRC and RRC contain some 2D Parameters (e.g. Useful Signal and Scattering Ratio for MRC). It would be useful if such parameters also could  be visualised in the Analytics View.

- When calculating regression coefficients, the number of decimal places of the result needs to be increased. At the Moment only two decimal places are printed. We suggest to print four.

**L1B:** 

- It would be nice if all 2D Parameters from the Analytics View parameter list could also be plotted in the Globe View.

- It would be desirable to also use "altitudes" as filter.

- The change from showing 1D Parameters (e.g. Mie velocity at DEM intersection) in the Analytics View to 2D (e.g. Mie HLOS winds) again does not work for me.  

- How are files from different orbits concatenated? There seems to be a gap in between two files.

- Mouse-over: I would prefer a tabular structure for the mouse-over output (as for the info box in the download panel), i.e. Parameter | Value (precision of 2 decimal places) | Unit

**Comment by santilland** [comment] 2018-09-11 10:31
Thanks for the feedback and pointing out some issues.
* The 2D parameters of AUX data need to be handled a little different then the rest of the AUX data, i created a new ticket to have this handled separately here #39.
* The visualization of the regression coefficients has been increased to a precision of 4, so it should show at least 4 meaningful digits.
* In relation to showing all 2D parameters also in the globe we will look into it, i created a separate ticket here #40
* (To altitude filter) We will also look at providing more filtering options
* Changing back to 2D is not intuitive, i am not sure how to adapt the user interface to make it so. What you need to do is set time for the x axis and mie/rayleigh altitude on the y axis. This gives you basically to curtain in one color. Then click on the cog symbol (top left) to open the rendering option for the selected parameter. There click on the label mie/rayleigh altitude, select apply colorscale and select the parameter you want to visualize. You can also apply colorscales to "1D" data.
* There was an issue where the curtain crossed from 179 to -179, this should be solved now. The gap was not between two files but was created because of this issue.
* A tabular form has been implemented now.

**Comment by santilland** [comment] 2019-11-05 14:12
I think all points have been addressed or at least tracked through other tickets so i will close this one for now. Feel free to comment with any other feedback.

**Closed by santilland** 2019-11-05 14:12 UTC
